### ISSUE TITLE
访问文章时出现迷之左偏移的样式

### ISSUE THREAD

**Issue by fimars** [geekplux/blog#4]
刚刚在阅读你的博客的时候，发现一个比较奇怪的样式问题。

### Env
- Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### 复现
1. https://geekplux.com/2018/09/26/blog-history 
2. https://geekplux.com/2014/02/02/goodbye_my_university.html 

不带.html后缀的前者会触发这个情况

### 猜测
出现偏移样式的时候`Chrome DevTools`给到了这样的Log, 是不是和最近迁移到Saber有关。

![image](https://user-images.githubusercontent.com/16299018/55855898-5673d100-5b9b-11e9-9c1d-99c7c43fa36f.png)

**Comment by fimars** [comment]
![image](https://user-images.githubusercontent.com/16299018/55861993-1ff18280-5baa-11e9-9ef5-db127917e6d8.png)

简单对比了一下Network记录，可能真的和路由处理有关，右边是出现偏移的情况（加载了404情况所需的js）

**Comment by geekplux** [comment]
破案了：由于开启了 netlify 的 pretty url，导致与博客本身的 permalinks 设置冲突，加载了 404 页面。

**Comment by fimars** [comment]
233，看到你们的讨论了，我就把issue close了
