### ISSUE TITLE
the plugin-seo does not work actually

### ISSUE THREAD

**Issue by h404bi** [geekplux/blog#6]
You can not access $siteConfig from the Saber Browser Api. There is not `this`(or to say, the saber instance) from the Saber Browser Api context, doc here: https://saber.land/docs/browser-apis.html

**Comment by geekplux** [comment]
LGTM, some `meta` tag added into `head`.

**Comment by h404bi** [comment]
I just found the reason. If you configure `rootOptions.head` in the theme's `saber-browser.js`, then it will force to use that and ignore whatever the plugin's settings, weird.
