### ISSUE TITLE
SEO: overwriting in blog posts

### ISSUE THREAD

**Issue by spekulatius** [geekplux/blog#8]
Hello @geekplux 

I was wondering if it's possible to overwrite keys from the $siteconfig in the particular template. Goal is to set keywords for a particular page/post. 

Peter

**Comment by geekplux** [comment]
I think it's possible to set the keywords according to the config of the Page if you can get page instance in saber-browser.js

**Comment by egoist** [comment]
set keywords for the page using page attributes (i.e. front matter in markdown).

**Comment by spekulatius** [comment]
I've opened a PR for it. https://github.com/geekplux/blog/pull/9

**Comment by geekplux** [comment]
any better way to get page attributes? @egoist https://github.com/geekplux/blog/pull/9/files#diff-5f854b8d77c13875ac7af2d7e277a0beR10

**Comment by spekulatius** [comment]
I was wondering this too. It's kinda not so nice 😂️

**Comment by geekplux** [comment]
just found https://saber.land/tutorial/tutorial.html#adding-document-title, seems it's convenient to set `<head>` in layout.

**Comment by egoist** [comment]
`head` is available in every component.

**Comment by spekulatius** [comment]
Hmmmm. With this, the functionality would move into the theme. Not really ideal I think. Any other ways to address this?

**Comment by egoist** [comment]
on nvm, didn't realize you're updating saber-browser.js in a plugin. that's
probably fine then.

Peter Thaleikis <notifications@github.com> 于 2019年5月28日周二 上午12:22写道：
